name: app_realtime_wrap
description: A package to extend Appwrite Realtime
version: 0.1.0+1

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  appwrite: ^12.0.4
  flutter:
    sdk: flutter
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
